name: "Diff porcelain"

description: "Checks if the current branch is clean and errors a custom message otherwise"

inputs:
  message:
    description: "Error message being used if changes are detected"
    required: true
    default: "Changes detected"
runs:
  using: "composite"
  steps:
    - name: Display changes
      shell: bash
      run: git status --porcelain

    - name: Error if changes detected
      shell: bash
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "${{ inputs.message }}"
          exit 1
        fi
